# Generated by Django 5.2.8 on 2026-03-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42),
        ),
    ]
