# Generated by Django 5.2.8 on 2026-03-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
